#!/bin/bash

echo ""
echo "=========================================="
echo "MANUAL STEPS REQUIRED"
echo "=========================================="
echo ""
echo "1. Spotlight shortcut:"
echo "   System Settings → Keyboard → Keyboard Shortcuts → Spotlight"
echo "   Disable 'Show Spotlight search'"
echo ""
echo "2. Alfred:"
echo "   Open Alfred → Preferences → General"
echo "   Set hotkey to Cmd+Space"
echo "   Grant accessibility permissions when prompted"
echo "   Set preferences folder"
echo ""
echo "3. iTerm2:"
echo "   Set font to a Nerd Font if using Powerlevel10k later"
echo ""
echo "=========================================="
